# Generated by Django 3.1.5 on 2021-02-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sw_os',
            field=models.CharField(default='', max_length=20, verbose_name='SW_OS'),
        ),
    ]
